Fix: parenthesised var was supposed to be 1-tuple?
Fixes error:

```
~/.pyenv/versions/3.8.12/envs/myproject/lib/python3.8/site-packages/holidays/countries/united_kingdom.py in _country_specific(self, year)
    158
    159         # Late Summer bank holiday (last Monday in August)
--> 160         if self.state not in ("Scotland") and year >= 1971:
    161             name = "Late Summer Bank Holiday"
    162             if self.state == "UK":

TypeError: 'in <string>' requires string as left operand, not NoneType
```